### PR TITLE
Add Custom Schema for use in Jamf Config Profiles

### PR DESCRIPTION
**Pull request by TheFuzzyTech**
**I haven't actually tested this in my deployment yet.**
Adds a custom schema for use with jamf config profiles.

### CODE REVIEW

**Comment by macmule** [comment]
hey @thefuzzyjew, did you test this?

Can you update with the items added in 2.0? https://github.com/dataJAR/jamJAR/releases/tag/2.0

**Comment by TheFuzzyTech** [comment]
Hoping to look at this over the weekend 🥳

**Comment by TheFuzzyTech** [comment]
Updated this PR to include items from 2.0

**Comment by macmule** [comment]
Thanks folks, and apologies for the delay.

I'll merge now, and then if we need to amend etc we can as needed.

Thanks again!

**Pull request merged**
